{% set name = "py-cpuinfo" %}
{% set version = "9.0.0" %}
{% set sha256 = "3cdbbf3fac90dc6f118bfd64384f309edeadd902d7c8fb17f02ffa1fc3f49690" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -v --no-deps --no-build-isolation
  entry_points:
    - cpuinfo = cpuinfo:main

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python

test:
  requires:
    - python
    - pip
  imports:
    - cpuinfo
  commands:
    - cpuinfo
    - pip check

about:
  home: https://github.com/workhorsy/py-cpuinfo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A module for getting CPU info with Python 2 & 3
  description: A module for getting CPU info with Python 2 & 3
  dev_url: https://github.com/workhorsy/py-cpuinfo
  doc_url: https://github.com/workhorsy/py-cpuinfo

extra:
  recipe-maintainers:
    - mstimberg
