{% set name = "py-cpuinfo" %}
{% set version = "3.3.0" %}
{% set sha256 = "c787b70a15f4bb54d338a46206c83a32ae7988e6e5568ab908752e7bccb1f62f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script_env:
    - PROCESSOR_ARCHITEW6432
    - PROCESSOR_ARCHITECTURE
    - PROCESSOR_IDENTIFIER
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - cpuinfo = cpuinfo:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - cpuinfo
  commands:
    - cpuinfo

about:
  home: https://github.com/workhorsy/py-cpuinfo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A module for getting CPU info with Python 2 & 3'
  dev_url: https://github.com/workhorsy/py-cpuinfo

extra:
  recipe-maintainers:
    - mstimberg
