travis:
  secure:
    BINSTAR_TOKEN: UgFxuum8WkyxgAFyvqVe9GKLpNMc9DHDSuwQukdqC6JDhMIgvFs0o7noSjMQwybx1iAe3dl/tyvtEkZt2ubl89gZ+YT+L3OYE0i+0TFByIAPQebCAgGWA7+zUyAs0Ta/i/Sl2UgYeM1OS8xlA1g8vncxSK4ZCXTxiutMeBRvfcGeuAYBtuUaHrwY0yLDr5ajU2wpZ9bLaSy2jYRMW1DgTOzM1gTSqKy6TMO0FVihR7ohHFKwU7RWhwvC4i/RGs+5aIQ8PLpFsc5tz/0p20sU3nvj0879P5W8Zk08KOVozkdR1yx412AZKjvUQpqEDlx7kR+vTDm1eG/RtU/Mbul4V8ikK+Ggl9DUufZcrKcME4ewwp91N1yb4rwv7LbcJ6WTS087cJAwEhPiYvbZZd7vz/BbaDVOPdX+7OVz39WR5iF1aBwBRwvIfcuflXIFQLAweMromOZaNTaK2ydV2poIcgKyKqj4ZOqIbpEgrPxE68QthwhCDhaPeqvH7jmY/+Dja2RmuRlwkHMYAuM7Qu1fmVSp5ZpEmpEyVVNGBBBa/bg2Jmj2wVTtcKCmIwBVb+tZQ+4ZR15AAdwR2xTTfLylqxIAYkHpkyXM+w0YEy3FfAt60O4t/kQQlPwn9RAopJj63szPWVrUlqAREKTsnkhexWb7L+5Y2zrYB1DwxFbOa2k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
