travis:
  secure:
    BINSTAR_TOKEN: 0qKXkQkkhDo4zPIA54g0iTo7QJ5zvhVxBe/+EVWtGSvx9Zir9a2Zd7eBiCLMBnYMX2Y46FZxj0PpHSqD4/DKNYRbFBpDBHrGjkidzkgGeTGvIsPJxuwPo/71jS++/znxtUJs1XznTCR7q1oyp/7PdgTdsmoLeOjSLC2XbJrGZV5EGFp/GTmrVqOSlltEexdEBRt6Xt1QgXgSCw3Yj0MJZuv9o95qFYYXSsoMbZk2M5HFivXnkclqj/iv70WJFd/W/zHKkW98jMcKo6t1t6z8A3rIAFpwQa05PnuMiJEnedAWKJEugxVX3Yw0aNGVd+JN7r9fRuGRyOWeh2LmgJjmgXSXJvm/JHBR9Jln5x9SIt4TlwXGOEm1QwZSZaDAmapttN5CtdM56A8n+sas6OAxqDojwC5BCbAhRgC5+Avi4PCNQ6o7UhNwr8BSW/eyRDPLU52uy5hapz8bQ5dq0kBsqGUJdeNrcWcbBOZhfLvTu4qzld13Pq5YBrEkS05c19SCwHQ0paDi56Ow5W3/uAREAt/UtspSE0zCx2Ug3pfB9mWedA3SOQMITizVr/k/XL7JWjwYRbZhRALZjy1acs3yEojVCo3KNys2nq+3vvvIVTBB9/xs4UXUkzG8NbX+Y2y3NRqxjRkiAk7U20hUbOgaDum01w2Fww29nDjX2tLw/Cw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
